#######################################################
# 
# DbUtil.py
# Python implementation of the Class DbUtil
# Generated by Enterprise Architect
# Created on:      27-4月-2023 19:55:34
# Original author: The Administrator
# 
#######################################################
import psycopg2.extras

class DbUtil:
	__dbname = 'atm'
	__host = 'localhost'
	__password = 'gitops123'
	__port = '5432'
	__user = 'dll'
	def __init__(self,dbname,host,password,port,user):
		self.dbname=dbname
		self.host=host
		self.password=password
		self.port=port
		self.user=user
	def createConnection(self):
		connection = psycopg2.connect(dbname=self.dbname, user=self.user, password=self.password, host=self.host, port=self.port)
		return connection

	def validateID(self, connection, id, pin):
		with connection.cursor(cursor_factory=psycopg2.extras.DictCursor) as cursor:
			# 根据顾客账号查出顾客信息
			sql = "select cid, cpin from g0atm0_customer where cid='%s';" % id
			cursor.execute(sql)
			item = cursor.fetchone()
			# 判断是否存在此顾客
			if item is None:
				print("无此顾客账号存在！")
				return False;
			# 获取顾客信息
			cid=item["cid"];
			cpin=item["cpin"];
			isLogin = self.validatePIN(pin,cpin);
			if isLogin:
				return True;
			else:
				return False;

	def validatePIN(self,cpin, pin):
		if pin != cpin:
			return False;
		else:
			return True;