pipeline {
    agent any
       stages{
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube'){
                    bat '''
                         sonar-scanner.bat -D"sonar.projectKey=g0atm" -D"sonar.sources=."
                         -D"sonar.host.url=http://localhost:9000"
                         -D"sonar.login=squ_e598b3daa9e60f9918d8dd18c42ad96f600d75be"
                        '''
               }
            }
        }
        stage('Quality Gate') {
            steps {
                script{
                    sleep(30)
                    timeout(time: 10, unit: 'MINUTES'){
                        //waitForQualityGate abortPipeline:true
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }
        stage('Build') {
            steps {
                bat 'python  -d -m py_compile g0atm0/Customer.py g0atm0/DbUtil.py'
            }
        }
        stage('Unit Test') {
            steps {
		        bat 'pytest --verbose --junit-xml test-reports/unittests.xml g0atm0/test_customer.py g0atm0/test_dbutil.py'
            }
            post {
               always {
                   junit 'xunit-reports/xunit-result-login.xml'
               }
            }
        }
        stage('Intergrate Test') {
            steps{
                bat 'python -m py_compile g0atm0/intergrateTest.py'
            }
             post {
               always {
                   junit 'coverage-reports/coverage-login.xml'
               }
            }

        }
        stage('Deliver') {
            steps {
                bat 'pyinstaller login_atm.spec'
            }
            post {
                success {
                    archiveArtifacts 'dist/login_atm.exe'
                }
            }
        }
        stage('Deploy Gitee'){
            steps{
                echo 'release gitee'
            }
        }
        stage('Execute login_atm.exe'){
            steps{
               bat '.\\dist\\login_atm.exe'
            }
        }
    }
}